name: backend
on: [pull_request]
defaults:
  run:
    working-directory: backend
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - id: diff
        run: git diff --shortstat origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} -- . | xargs -I{} echo "::set-output name=diff::{}"
      - if: steps.diff.outputs.diff != ''
        name: check
        uses: reviewdog/action-golangci-lint@v1
        with:
          workdir: backend
          reporter: github-check
          filter_mode: nofilter
          level: info
      - if: steps.diff.outputs.diff != ''
        name: review
        uses: reviewdog/action-golangci-lint@v1
        with:
          workdir: backend
          reporter: github-pr-review
          filter_mode: nofilter
          level: info
