name: backend
on:
  pull_request:
    paths:
      - 'backend/**'
defaults:
  run:
    working-directory: backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.1
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      -
        name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          workdir: backend
          reporter: github-pr-review
          filter_mode: nofilter
          level: info
