name: backend
on: [pull_request]
defaults:
  run:
    working-directory: backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: diff
        run: git diff --shortstat origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} -- . | xargs -I{} echo "::set-output name=diff::{}"
      - if: steps.diff.outputs.diff != ''
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.1
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - id: diff
        run: git diff --shortstat origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} -- . | xargs -I{} echo "::set-output name=diff::{}"
      - if: steps.diff.outputs.diff != ''
        name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          workdir: backend
          reporter: github-pr-review
          level: info
